import { CardSkeleton } from "@/components/ui/loading-skeletons";
import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { Briefcase, Search, Plus, MapPin, ArrowRight, Sparkles, SlidersHorizontal, X } from "lucide-react";
import { motion } from "framer-motion";
import Navbar from "@/components/landing/Navbar";
import BackButton from "@/components/ui/back-button";
import CreateJobDialog from "@/components/jobs/CreateJobDialog";
import JobCard from "@/components/jobs/JobCard";
import type { Database } from "@/integrations/supabase/types";

type Job = Database["public"]["Tables"]["jobs"]["Row"];
type JobType = Database["public"]["Enums"]["job_type"];
const jobTypeLabels: Record<string,string>={emploi:"Emploi",mission:"Mission freelance",stage:"Stage",cofounder:"Co-fondateur",advisory:"Advisory"};
const PAGE_SIZE=20;
const Jobs=()=>{const {role}=useAuth();const navigate=useNavigate();const[jobs,setJobs]=useState<Job[]>([]);const[loading,setLoading]=useState(true);const[loadingMore,setLoadingMore]=useState(false);const[hasMore,setHasMore]=useState(true);const[search,setSearch]=useState("");const[typeFilter,setTypeFilter]=useState("all");const[showCreate,setShowCreate]=useState(false);
 const fetchJobs=async(page=0)=>{if(page===0)setLoading(true);else setLoadingMore(true);let query=supabase.from("jobs").select("*").eq("is_active",true).order("created_at",{ascending:false});if(typeFilter!=="all")query=query.eq("job_type",typeFilter as JobType);const{data,error}=await query.range(page*PAGE_SIZE,page*PAGE_SIZE+PAGE_SIZE-1);if(error)toast.error("Impossible de charger les opportunités");else{setJobs(prev=>page===0?(data||[]):[...prev,...(data||[])]);setHasMore((data||[]).length===PAGE_SIZE)}setLoading(false);setLoadingMore(false)};
 useEffect(()=>{fetchJobs(0)},[typeFilter]);const filteredJobs=jobs.filter(j=>{if(!search)return true;const s=search.toLowerCase();return Boolean(j.title?.toLowerCase().includes(s)||j.company_name?.toLowerCase().includes(s)||j.sector?.toLowerCase().includes(s)||j.city?.toLowerCase().includes(s)||(j.skills_required||[]).some((sk:string)=>sk.toLowerCase().includes(s)))});const canPost=role==="startup"||role==="admin";const activeFilter=search||typeFilter!=="all";
 return <div className="min-h-screen bg-background"><Navbar/><main className="mx-auto max-w-7xl px-4 pb-16 pt-28 sm:px-6 lg:px-8"><BackButton fallbackTo="/" /><section className="mb-8 overflow-hidden rounded-3xl border border-border bg-card p-6 sm:p-10"><div className="flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-primary"><Sparkles className="h-4 w-4"/>Opportunités</div><h1 className="font-display text-3xl font-bold tracking-tight sm:text-5xl">Trouvez la prochaine opportunité qui vous correspond.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">Emplois, missions, stages, co-fondateurs et advisory au sein de l'écosystème Union'S.</p></div>{canPost&&<Button onClick={()=>setShowCreate(true)} className="shrink-0 bg-gradient-gold text-primary-foreground"><Plus className="mr-2 h-4 w-4"/>Publier une offre</Button>}</div></section>
 <section className="sticky top-[72px] z-20 mb-8 rounded-2xl border border-border bg-background/95 p-3 shadow-sm backdrop-blur-xl sm:p-4"><div className="flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input aria-label="Rechercher une opportunité" placeholder="Titre, compétence, entreprise ou ville..." value={search} onChange={e=>setSearch(e.target.value)} className="h-11 border-border pl-10 pr-10"/>{search&&<button onClick={()=>setSearch("")} aria-label="Effacer la recherche" className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"><X className="h-4 w-4"/></button>}</div><Select value={typeFilter} onValueChange={setTypeFilter}><SelectTrigger className="h-11 w-full lg:w-[230px]"><SlidersHorizontal className="mr-2 h-4 w-4"/><SelectValue placeholder="Type d'opportunité"/></SelectTrigger><SelectContent><SelectItem value="all">Toutes les opportunités</SelectItem>{Object.entries(jobTypeLabels).map(([key,label])=><SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select></div><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{Object.entries(jobTypeLabels).map(([key,label])=><button key={key} onClick={()=>setTypeFilter(typeFilter===key?"all":key)} className={`shrink-0 rounded-full border px-3 py-1.5 text-xs font-medium transition-colors ${typeFilter===key?"border-primary bg-primary text-primary-foreground":"border-border bg-card text-muted-foreground hover:border-primary/40 hover:text-foreground"}`}>{label}</button>)}</div></section>
 <div className="mb-5 flex items-end justify-between gap-4"><div><h2 className="font-display text-2xl font-bold">Opportunités disponibles</h2><p className="mt-1 text-sm text-muted-foreground">{filteredJobs.length} résultat{filteredJobs.length>1?"s":""}{activeFilter?" correspondant à votre recherche":""}</p></div></div>
 {loading?<div className="grid gap-5 md:grid-cols-2">{Array.from({length:4}).map((_,i)=><CardSkeleton key={i}/>)}</div>:filteredJobs.length===0?<div className="rounded-2xl border border-dashed border-border bg-card p-12 text-center"><Briefcase className="mx-auto mb-4 h-10 w-10 text-muted-foreground/50"/><h3 className="text-lg font-semibold">Aucune opportunité trouvée</h3><p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">Modifiez votre recherche ou vos filtres pour découvrir d'autres opportunités.</p>{activeFilter&&<Button variant="outline" className="mt-5" onClick={()=>{setSearch("");setTypeFilter("all")}}>Réinitialiser</Button>}</div>:<><div className="grid gap-5 md:grid-cols-2">{filteredJobs.map((job,i)=><motion.article key={job.id} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:Math.min(i*.025,.2)}} className="group rounded-2xl border border-border bg-card p-1 transition-all hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-lg"><div className="relative"><JobCard job={job} onApply={()=>navigate(`/jobs/${job.id}`)}/><div className="pointer-events-none absolute right-4 top-4 flex items-center gap-1 rounded-full bg-background/90 px-2 py-1 text-[11px] font-medium text-muted-foreground shadow-sm"><MapPin className="h-3 w-3"/>{job.city||"Afrique"}</div></div></motion.article>)}</div>{hasMore&&<div className="mt-8 flex justify-center"><Button variant="outline" onClick={()=>fetchJobs(Math.ceil(jobs.length/PAGE_SIZE))} disabled={loadingMore}>{loadingMore?"Chargement...":"Charger plus"}<ArrowRight className="ml-2 h-4 w-4"/></Button></div>}</>}
 </main><CreateJobDialog open={showCreate} onOpenChange={setShowCreate} onCreated={fetchJobs}/></div>};export default Jobs;
